/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as EventsEventIdIndexRouteImport } from './routes/events.$eventId.index'
import { Route as EventsEventIdTimelineRouteImport } from './routes/events.$eventId.timeline'
import { Route as EventsEventIdStatusRouteImport } from './routes/events.$eventId.status'
import { Route as EventsEventIdSetupRouteImport } from './routes/events.$eventId.setup'
import { Route as EventsEventIdPrintRouteImport } from './routes/events.$eventId.print'
import { Route as EventsEventIdPeopleRouteImport } from './routes/events.$eventId.people'
import { Route as EventsEventIdDayOfRouteImport } from './routes/events.$eventId.day-of'
import { Route as EventsEventIdActivitiesActivityIdRouteImport } from './routes/events.$eventId.activities.$activityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdTimelineRoute = EventsEventIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdStatusRoute = EventsEventIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdSetupRoute = EventsEventIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdPrintRoute = EventsEventIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdPeopleRoute = EventsEventIdPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdDayOfRoute = EventsEventIdDayOfRouteImport.update({
  id: '/day-of',
  path: '/day-of',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdActivitiesActivityIdRoute =
  EventsEventIdActivitiesActivityIdRouteImport.update({
    id: '/activities/$activityId',
    path: '/activities/$activityId',
    getParentRoute: () => EventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/$eventId/day-of': typeof EventsEventIdDayOfRoute
  '/events/$eventId/people': typeof EventsEventIdPeopleRoute
  '/events/$eventId/print': typeof EventsEventIdPrintRoute
  '/events/$eventId/setup': typeof EventsEventIdSetupRoute
  '/events/$eventId/status': typeof EventsEventIdStatusRoute
  '/events/$eventId/timeline': typeof EventsEventIdTimelineRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/activities/$activityId': typeof EventsEventIdActivitiesActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId/day-of': typeof EventsEventIdDayOfRoute
  '/events/$eventId/people': typeof EventsEventIdPeopleRoute
  '/events/$eventId/print': typeof EventsEventIdPrintRoute
  '/events/$eventId/setup': typeof EventsEventIdSetupRoute
  '/events/$eventId/status': typeof EventsEventIdStatusRoute
  '/events/$eventId/timeline': typeof EventsEventIdTimelineRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/events/$eventId/activities/$activityId': typeof EventsEventIdActivitiesActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/$eventId/day-of': typeof EventsEventIdDayOfRoute
  '/events/$eventId/people': typeof EventsEventIdPeopleRoute
  '/events/$eventId/print': typeof EventsEventIdPrintRoute
  '/events/$eventId/setup': typeof EventsEventIdSetupRoute
  '/events/$eventId/status': typeof EventsEventIdStatusRoute
  '/events/$eventId/timeline': typeof EventsEventIdTimelineRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/events/$eventId/activities/$activityId': typeof EventsEventIdActivitiesActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$eventId'
    | '/events/$eventId/day-of'
    | '/events/$eventId/people'
    | '/events/$eventId/print'
    | '/events/$eventId/setup'
    | '/events/$eventId/status'
    | '/events/$eventId/timeline'
    | '/events/$eventId/'
    | '/events/$eventId/activities/$activityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$eventId/day-of'
    | '/events/$eventId/people'
    | '/events/$eventId/print'
    | '/events/$eventId/setup'
    | '/events/$eventId/status'
    | '/events/$eventId/timeline'
    | '/events/$eventId'
    | '/events/$eventId/activities/$activityId'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/events/$eventId/day-of'
    | '/events/$eventId/people'
    | '/events/$eventId/print'
    | '/events/$eventId/setup'
    | '/events/$eventId/status'
    | '/events/$eventId/timeline'
    | '/events/$eventId/'
    | '/events/$eventId/activities/$activityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/timeline': {
      id: '/events/$eventId/timeline'
      path: '/timeline'
      fullPath: '/events/$eventId/timeline'
      preLoaderRoute: typeof EventsEventIdTimelineRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/status': {
      id: '/events/$eventId/status'
      path: '/status'
      fullPath: '/events/$eventId/status'
      preLoaderRoute: typeof EventsEventIdStatusRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/setup': {
      id: '/events/$eventId/setup'
      path: '/setup'
      fullPath: '/events/$eventId/setup'
      preLoaderRoute: typeof EventsEventIdSetupRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/print': {
      id: '/events/$eventId/print'
      path: '/print'
      fullPath: '/events/$eventId/print'
      preLoaderRoute: typeof EventsEventIdPrintRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/people': {
      id: '/events/$eventId/people'
      path: '/people'
      fullPath: '/events/$eventId/people'
      preLoaderRoute: typeof EventsEventIdPeopleRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/day-of': {
      id: '/events/$eventId/day-of'
      path: '/day-of'
      fullPath: '/events/$eventId/day-of'
      preLoaderRoute: typeof EventsEventIdDayOfRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/activities/$activityId': {
      id: '/events/$eventId/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/events/$eventId/activities/$activityId'
      preLoaderRoute: typeof EventsEventIdActivitiesActivityIdRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
  }
}

interface EventsEventIdRouteChildren {
  EventsEventIdDayOfRoute: typeof EventsEventIdDayOfRoute
  EventsEventIdPeopleRoute: typeof EventsEventIdPeopleRoute
  EventsEventIdPrintRoute: typeof EventsEventIdPrintRoute
  EventsEventIdSetupRoute: typeof EventsEventIdSetupRoute
  EventsEventIdStatusRoute: typeof EventsEventIdStatusRoute
  EventsEventIdTimelineRoute: typeof EventsEventIdTimelineRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  EventsEventIdActivitiesActivityIdRoute: typeof EventsEventIdActivitiesActivityIdRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdDayOfRoute: EventsEventIdDayOfRoute,
  EventsEventIdPeopleRoute: EventsEventIdPeopleRoute,
  EventsEventIdPrintRoute: EventsEventIdPrintRoute,
  EventsEventIdSetupRoute: EventsEventIdSetupRoute,
  EventsEventIdStatusRoute: EventsEventIdStatusRoute,
  EventsEventIdTimelineRoute: EventsEventIdTimelineRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  EventsEventIdActivitiesActivityIdRoute:
    EventsEventIdActivitiesActivityIdRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
